### ISSUE TITLE
Storybook not working when create new project in open-wc

### ISSUE THREAD

**Issue by Rajkumar-MP** [open-wc/create#16]
When i create new applicaiton using open-wc  and try to run the storybook, i am facing below issues.

  Error: [@web/dev-server-storybook] The file C:/Users/Ghost/Desktop/Training/web-app/stories/web-app.stories.js is not accessible by the browser because it is outside the root directory C:\Users\Ghost\Desktop\Training\web-app. Change the rootDir option to include this directory.
      at createError (C:\Users\Ghost\Desktop\Training\web-app\node_modules\@web\dev-server-storybook\dist\shared\utils.js:9:12)
      at Object.

When i do the debugging, its look like **Root directory and filepath url slash format is different**, so facing an issue, the format look like below

RootDir ::  C:\Users\Ghost\Desktop\Training\web-app
FilePath ::  C:/Users/Ghost/Desktop/Training/web-app/stories/web-app.stories.js

**Comment by LarsDenBakker** [comment]
Thanks for reporting, can you try if @web/dev-server-storybook@0.3.4 solves the issue?

**Comment by Rajkumar-MP** [comment]
updated dev-server-storybook to @0.3.4 version, still i am facing same issue.

**Comment by Halt001** [comment]
Same here, created a default webcomponent project with `npm init @open-wc` en ran `npm run storybook`. And then you see the error about the file not in the webroot. As TS mentioned it looks like it is a slash type in path issue. This works without a problem on MacOS.

**Comment by LarsDenBakker** [comment]
Sorry about this guys... could you try again using @web/dev-server-storybook@0.3.5 ?

**Comment by Rajkumar-MP** [comment]
Perfect. now its working as expected. Thanks @LarsDenBakker
