### ISSUE TITLE
Utility of common-repo/templates/static/

### ISSUE THREAD

**Issue by movrack** [open-wc/create#31]
Hello,
Which is the utility of `common-repo/templates/static/` ?
It generate the following files:
- .editorconfig 
- licence

Concerning editorconfig, all his job is already made with the configuration of prettier and lint from ´https://github.com/open-wc/create/blob/master/src/generators/linting/templates/package.json´

Concerning license, it is dependent of the project user, here a MIT license file is generated but not every body is using it. 
1) can be MIT or other type of license
2) What for people doing without (private cases)
In my case we are doing "private" package for the enterprise and we have to remove that file every time we generate a component. 

Can't it be removed, or chosen with an option ?

So to resume, does common-repo is necessary since it is the only 2 files added.

**Comment by jorenbroekema** [comment]
Agreed, I think both files should just be deleted, the editorconfig is now redundant with prettier, and the license doesn't cover a large enough majority to justify scaffolding it as MIT in my opinion.

**Comment by daKmoR** [comment]
Having a default license makes sense for an open-source tool and as Open Web Component is all about helping you along.
And having a MIT license is better than no license.
If you have a different license preference then you know about the topic and can take action, however, many people don't even understand it so for them having a default license make sense.

So I would like to keep the license.

**Comment by movrack** [comment]
And can't we add an option /question in the form like 
"Is it an open-source project ? (generating license file)" yes/no

Or something like, yes by default

**Comment by jorenbroekema** [comment]
That's kinda tough as there are many open source licenses, so one could argue for a whole menu of licenses. 

I'm planning to write some docs on extending open-wc/create but for now you can do:
```js
import { deleteVirtualFile } from '@open-wc/create';
```
and then in your Mixin or base generator:
```js
async execute() {
  deleteVirtualFile(this.destinationPath('LICENSE'));
} 
```
