### ISSUE TITLE
Does not offer option to build with rollup

### ISSUE THREAD

**Issue by WickyNilliams** [open-wc/create#45]
The docs here imply that it should be possible to configure rollup for building through the generator, but I am not seeing any such option. https://open-wc.org/docs/building/rollup/

There is some scaffolding here, but it doesn't seem to be used https://github.com/open-wc/create/tree/master/src/generators/building-rollup-ts

Am I missing something?

**Comment by Westbrook** [comment]
Building is currently available in most or all option trees. If you have additional information on what you'd like to see here, please open a new URL with reproduction steps where in you do not find this option available to you.
