### ISSUE TITLE
Possible to remove tsc and use plugins instead?

### ISSUE THREAD

**Issue by dejan9393** [open-wc/create#71]
Hi,

Currently the build step first runs tsc before running through either rollup and webpack. For me, this seems like it could be optimised by using the relevant plugins, i.e. @rollup/plugin-typescript for rollup and ts-loader for webpack.

The current issue i'm trying to workaround is static assets (such as css) not being including in the out-tsc folder, requiring an extra build step. I'm assuming this would workaround that issue?

**Comment by Westbrook** [comment]
Using `tsc` allows for a normalization of TS processing across build, dev, test, and demo processes, so we're not likely to move away from it unless it can be replaced globally for all of these features. If you've got any ideas, we'd be happy to see full scope suggestions in a new issue.
