### ISSUE TITLE
Old litElement HMR preset is referenced by template

### ISSUE THREAD

**Issue by drk-mtr** [open-wc/create#81]
Thanks for the brilliant server, test runner & templates - they're a pleasure to use!

I was wondering why HMR wasn't working, so I had just started implementing a base class based on this guide: https://open-wc.org/docs/development/hot-module-replacement/

Then I started thinking "surely someone cleverer than me has already done this" and of course they have - the preset just needed changing from `presets.litElement` to `presets.lit` in `web-dev-server.config.mjs`. Would it be worth updating the template here?

https://github.com/open-wc/create/blob/c6558e911ef57687992f34b6c31fe547e4d8d177/src/generators/app-lit-element/templates/static/web-dev-server.config.mjs#L22

**Comment by maerten** [comment]
Submitted a PR since I ran into this issue today too

**Comment by tornadoblue** [comment]
I also spent hours trying to figure out why this wasn't working.  Hope the PR gets accepted soon to avoid other people running into this issue.

**Comment by Westbrook** [comment]
fixed by https://github.com/open-wc/create/pull/90
